### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [maximkin-alek/maximkin-alek.github.io-form#3]
Добрый вечер. Благодарю за проделанную работу.
К сожалению, текущая реализация содержит ряд недостатков не позволяющих мне засчитать ее на данной итерации:

## Репозиторий
**Можно лучше** файл .nojekyll не используется и может быть удален из репозитория
**Можно лучше**: Добавить .gitignore.
.gitignore должен содержать правила, исключающие попадание временных и\или системных файлов в репозиторий.
В случае если вы затрудняетесь с составлением списка базовых правил можете воспользоваться сервисом-генератором, например gitignore.io

## Регулярные выражения
**Можно лучше** Квантификатор `{1}` можно не использовать. Он не играет никакой роли.
**Можно лучше** запись (http|https)? эквивалентна https?

### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`denis_zlocate@gmail.academy` - имя пользователя (часть до @) может включать в себя единичный (подряд) подчерк.
`some-extra-long-name@some.extra.long.domain.name` - доменное имя может включать в себя произвольное число поддоменов

### Адрес сайта
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`http://127.0.0`. - некорректный IP, точка на конце

**Comment by maximkin-alek** [comment]
Добрый вечер, благодарю за комментарии. Внёс правки.

**Comment by zlocate** [comment]
**Можно лучше** квантификатор {1,1} можно не использовать, он не играет никакой роли (по-умолчанию при обработке регулярного выражения считается, что указанный символ встречается 1 раз)

**Comment by zlocate** [comment]
Добрый день.
Остался один кейс, требующий проработки:
### Адрес сайта
**Нужно исправить** следующие некорректные кейсы проходят валидацию
http://google.ru:/path/to/deep - отсутствует номер порта после символа `:`

**Comment by maximkin-alek** [comment]
Добрый вечер, спасибо, поправил.

**Comment by zlocate** [comment]
Добрый день. Работа принята.Желаю успехов в дальнейшем прохождении курса.

**Comment by maximkin-alek** [comment]
Спасибо!
